### PR TITLE
Feature/dsa 970 add hook for click manipulation simple

### PR DESCRIPTION
**Pull request by ptusch**
This PR does one thing:
* Handle onShow and onHide event in the inline datepicker in order to manipulate iOS exclusive behavior.

Note:
I did not update from upstream because the behavior for the datepicker is broken and it can't call the `changeValue` callback correctly (only calls it when the datepicker is shown)

Ref 1: https://github.com/valor-software/ngx-bootstrap/issues/3174
Ref 2: https://github.com/valor-software/ngx-bootstrap/issues/2810
Ref 3: https://github.com/valor-software/ngx-bootstrap/issues/5683

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] ~added/updated tests.~
 - [ ] ~added/updated API documentation.~
 - [ ] ~added/updated demos.~

### CODE REVIEW

**Review by mdm — APPROVED** [review]
:+1:

**Review by lasong — APPROVED** [review]
LGTM

**Comment by daniloff200** [comment]
hello :)

My name is Dmitry, and I'm from ngx-bootstrap team, and saw this PR mentioned in issue, related to double-tap in iOS

Does this solution was really helpful? If so, I would like to add this to next release, and fix this issue for all users of the library, of course, with your authorship on it

**Comment by daniloff200** [comment]
@lasong  @ptusch 
hey!
Can you help me with question above?

**Comment by ptusch** [comment]
@daniloff200 Good day.
Yes, it worked like a charm (but it kinda felt dirty in a way)

**Comment by daniloff200** [comment]
Good morning, @ptusch !
Strange for me
I've tried to implement the same solution in ngx-bootstrap codebase, also, tried to clone your ngx-bootstrap fork, but, still see this issue with doubletap 
Magic!

**Comment by simone-schaefer** [comment]
@daniloff200  The fix here is only part of the solution. In our calling component, we still need to overwrite the hoverHandler as described here: https://github.com/valor-software/ngx-bootstrap/issues/3174#issuecomment-380301209 
This fix here only adds the onShown hook to the inline datepicker which does not have it by default.

**Comment by daniloff200** [comment]
Thanks @ptusch !

Actually, I've found the root cause of that issue, and, looks like https://github.com/valor-software/ngx-bootstrap/issues/5821  should fix that.

Feel free to try this solution in your project too

**Pull request merged**
